### ISSUE TITLE
Version number not supported by OGL driver

### ISSUE THREAD

**Issue by oakio** [MailRuChamps/raic-2019#10]
Есть возможность снизить требования к версии `OpenGL` для `aicup2019.exe`?

> INFO - Guessed window DPI factor: 1
> INFO - GL version: "2.1.0 - Build 8.15.10.2900"
> ERROR - panicked at 'called `Result::unwrap()` on an `Err` value: ShaderCompilationError { log: "ERROR: 0:1: \'\' :  Version number not supported by OGL driver\nERROR: 0:2: \'precision\' : syntax error parse error\n\n\u{0}" }', src\libcore\result.rs:1084:5
> ERROR - stack backtrace:
>    0: backtrace::backtrace::trace
>    1: backtrace::capture::Backtrace::new
>    2: batbox::logger::init_with_level::{{closure}}
>    3: std::panicking::rust_panic_with_hook
>              at src\libstd/panicking.rs:481
>    4: std::panicking::continue_panic_fmt
>              at src\libstd/panicking.rs:384
>    5: rust_begin_unwind
>              at src\libstd/panicking.rs:311
>    6: core::panicking::panic_fmt
>              at src\libcore/panicking.rs:85
>    7: core::result::unwrap_failed
>              at src\libcore/result.rs:1084
>    8: geng_core::draw_2d::Draw2D::new
>    9: geng_core::context::Geng::new
>   10: aicup2019::run_with
>   11: aicup2019::run
>   12: std::rt::lang_start::{{closure}}
>   13: std::rt::lang_start_internal::{{closure}}
>              at src\libstd/rt.rs:49
>       std::panicking::try::do_call
>              at src\libstd/panicking.rs:296
>   14: __rust_maybe_catch_panic
>              at src\libpanic_unwind/lib.rs:80
>   15: std::panicking::try
>              at src\libstd/panicking.rs:275
>       std::panic::catch_unwind
>              at src\libstd/panic.rs:394
>       std::rt::lang_start_internal
>              at src\libstd/rt.rs:48
>   16: main
>   17: __tmainCRTStartup
>              at ./mingw-w64-crt/crt/crtexe.c:339
>   18: mainCRTStartup
>              at ./mingw-w64-crt/crt/crtexe.c:223
>   19: _report_error
>   20: _report_error

**Comment by kuviman** [comment]
Не уверен, что получится что то сделать. Поддерживается OpenGL версии >3.3

**Comment by oakio** [comment]
Можно добавить флаг отключающий UI? Чтобы просто запускался сервер и симулятор.
