### ISSUE TITLE
Go: ошибка в PlayerId

### ISSUE THREAD

**Issue by prospero78** [MailRuChamps/raic-2019#12]
При попытке вычислить своего игрока и чужого -- PlayerId совпадает.
Причём, игроков 2, а номер 181, 193...
Где-то происходит копирование указателя врага при переборе в назначенного врага. Приходится делать полную копию структуры выбранного врага и назначать при выборе `PlayerId=-1`

**Comment by sflechie** [comment]
А как перебираете?

**Comment by 0fs** [comment]
> При попытке вычислить своего игрока и чужого -- PlayerId совпадает.
> Причём, игроков 2, а номер 181, 193...
> Где-то происходит копирование указателя врага при переборе в назначенного врага. Приходится делать полную копию структуры выбранного врага и назначать при выборе `PlayerId=-1`

А как перебираете?

**Comment by iziCode** [comment]
Пример на golang не работает, юнит не двигается

**Comment by 0fs** [comment]
> Пример на golang не работает, юнит не двигается

https://github.com/MailRuChamps/raic-2019/pull/18 реквест уже лежит

**Comment by prospero78** [comment]
> А как перебираете?

В цикле по словарю игроков.
Дело не в том, _как я перебираю_, а в том, что использую дефолтную стратегию -- враг создаётся как указатель на игрока. И при дальнейшей работе с ним -- оказывается, что там какой-то мусор.
Поэтому, приходится создавать реальную копию структуры `Unit`, и предварительно устанавливать её `PlayerId=-1`

**Comment by 0fs** [comment]
> Поэтому, приходится создавать реальную копию структуры `Unit`, и предварительно устанавливать её `PlayerId=-1`

А можно просто перебирать по-другому)

**Comment by prospero78** [comment]
Как по другому? обращаться к unsafe и получать ссылку?

**Comment by 0fs** [comment]
> Как по другому? обращаться к unsafe и получать ссылку?

https://github.com/MailRuChamps/raic-2019/pull/18

**Comment by kuviman** [comment]
#21 merged
