### ISSUE TITLE
Crash macOS

### ISSUE THREAD

**Issue by Davarg** [MailRuChamps/raic-2019#17]
I can't start macOS client. It's always crashed
System - macOS Catalina 10.15.1

<details>
<summary>Logs</summary>

INFO - GL version: "4.1 INTEL-14.2.16"
INFO - Loading "./assets/level/jumper_1.png"
INFO - Loading "./assets/level/jumper_2.png"
INFO - Loading "./assets/level/wall_down_R.png"
INFO - Loading "./assets/level/wall_down_C.png"
INFO - Loading "./assets/level/wall_down_solo.png"
INFO - Loading "./assets/level/wall_L.png"
INFO - Loading "./assets/level/wall_C.png"
INFO - Loading "./assets/level/wall_R.png"
INFO - Loading "./assets/level/wall_solo.png"
INFO - Loading "./assets/level/window_L.png"
INFO - Loading "./assets/level/window_R.png"
INFO - Loading "./assets/level/window_C.png"
INFO - Loading "./assets/level/window_solo.png"
INFO - Loading "./assets/level/railing_L.png"
INFO - Debug overlay initialized
INFO - Loading "./assets/level/jumper_3.png"
INFO - Loading "./assets/level/railing_C.png"
INFO - Loading "./assets/level/railing_R.png"
INFO - Loading "./assets/level/wall_down_L.png"
INFO - Loading "./assets/level/platform_R.png"
INFO - Loading "./assets/level/platform_solo.png"
INFO - Loading "./assets/level/floor_1.png"
INFO - Loading "./assets/level/platform_L.png"
INFO - Loading "./assets/level/door.png"
INFO - Loading "./assets/level/platform_C.png"
INFO - Loading "./assets/level/floor_2.png"
INFO - Loading "./assets/level/platform_small_L.png"
INFO - Loading "./assets/level/platform_small_C.png"
INFO - Loading "./assets/./city.png"
INFO - Loading "./assets/level/platform_small_R.png"
INFO - Loading "./assets/level/stairs.png"
INFO - Loading "./assets/./cloud.png"
INFO - Loading "./assets/level/platform_small_solo.png"
INFO - Loading "./assets/unit/1/jump/3.png"
INFO - Loading "./assets/./explosion.png"
INFO - Loading "./assets/unit/1/jump/2.png"
INFO - Loading "./assets/unit/1/rise/1.png"
INFO - Loading "./assets/unit/1/jump/1.png"
INFO - Loading "./assets/unit/1/rise/2.png"
INFO - Loading "./assets/unit/1/rise/3.png"
INFO - Loading "./assets/unit/1/rise/4.png"
INFO - Loading "./assets/unit/1/walk/2.png"
INFO - Loading "./assets/unit/1/rise/5.png"
INFO - Loading "./assets/unit/1/walk/1.png"
INFO - Loading "./assets/unit/1/rise/6.png"
INFO - Loading "./assets/unit/1/walk/5.png"
INFO - Loading "./assets/unit/1/walk/4.png"
INFO - Loading "./assets/unit/1/walk/3.png"
INFO - Loading "./assets/unit/1/walk/6.png"
INFO - Loading "./assets/unit/1/hand.png"
INFO - Loading "./assets/unit/2/jump/1.png"
INFO - Loading "./assets/unit/2/jump/2.png"
INFO - Loading "./assets/unit/2/jump/3.png"
INFO - Loading "./assets/unit/1/head.png"
INFO - Loading "./assets/unit/1/stay.png"
INFO - Loading "./assets/unit/2/rise/1.png"
INFO - Loading "./assets/unit/2/rise/2.png"
INFO - Loading "./assets/unit/2/rise/3.png"
INFO - Loading "./assets/unit/2/rise/4.png"
INFO - Loading "./assets/unit/2/rise/5.png"
INFO - Loading "./assets/unit/2/rise/6.png"
INFO - Loading "./assets/unit/2/walk/3.png"
INFO - Loading "./assets/unit/2/walk/2.png"
INFO - Loading "./assets/unit/2/walk/5.png"
INFO - Loading "./assets/unit/2/walk/6.png"
INFO - Loading "./assets/unit/2/walk/4.png"
INFO - Loading "./assets/unit/2/walk/1.png"
INFO - Loading "./assets/unit/2/hand.png"
INFO - Loading "./assets/unit/2/head.png"
INFO - Loading "./assets/unit/2/stay.png"
INFO - Loading "./assets/unit/3/jump/3.png"
INFO - Loading "./assets/unit/3/jump/1.png"
INFO - Loading "./assets/unit/3/rise/1.png"
INFO - Loading "./assets/unit/3/jump/2.png"
INFO - Loading "./assets/unit/3/rise/2.png"
INFO - Loading "./assets/unit/3/rise/3.png"
INFO - Loading "./assets/unit/3/rise/6.png"
INFO - Loading "./assets/unit/3/rise/5.png"
INFO - Loading "./assets/unit/3/walk/2.png"
INFO - Loading "./assets/unit/3/walk/3.png"
INFO - Loading "./assets/unit/3/rise/4.png"
INFO - Loading "./assets/unit/3/walk/1.png"
INFO - Loading "./assets/unit/3/walk/4.png"
INFO - Loading "./assets/unit/3/walk/5.png"
INFO - Loading "./assets/unit/3/walk/6.png"
INFO - Loading "./assets/unit/3/hand.png"
INFO - Loading "./assets/unit/3/head.png"
INFO - Loading "./assets/guns/assault_rifle/bullet.png"
INFO - Loading "./assets/guns/assault_rifle/muzzle_flash_1.png"
INFO - Loading "./assets/unit/3/stay.png"
INFO - Loading "./assets/guns/assault_rifle/gun.png"
INFO - Loading "./assets/guns/assault_rifle/muzzle_flash_2.png"
INFO - Loading "./assets/guns/pistol/gun.png"
INFO - Loading "./assets/guns/pistol/bullet.png"
INFO - Loading "./assets/guns/pistol/muzzle_flash.png"
INFO - Loading "./assets/loot/health_pack.png"
INFO - Loading "./assets/loot/mine.png"
INFO - Loading "./assets/guns/rocket_launcher/muzzle_flash.png"
INFO - Loading "./assets/guns/rocket_launcher/gun.png"
INFO - Loading "./assets/loot/assault_rifle.png"
INFO - Loading "./assets/loot/rocket_launcher.png"
INFO - Loading "./assets/guns/rocket_launcher/bullet.png"
INFO - Loading "./assets/mine/triggered.png"
INFO - Loading "./assets/loot/pistol.png"
INFO - Loading "./assets/mine/preparing.png"
INFO - Loading "./assets/./explosion.wav"
INFO - Loading "./assets/mine/idle.png"
INFO - Loading "./assets/./pickup.wav"
INFO - Loading "./assets/./hit.wav"
INFO - Loading "./assets/./guns/pistol/shoot.wav"
INFO - Loading "./assets/./heal.wav"
INFO - Loading "./assets/./guns/assault_rifle/shoot.wav"
INFO - Loading "./assets/./guns/rocket_launcher/shoot.wav"
ERROR - panicked at 'Failed to load assets: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

./assets/level/jumper_1.png', src/libcore/result.rs:1084:5
ERROR - stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: batbox::logger::init_with_level::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::result::unwrap_failed
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  10: <geng_core::loading_screen::LoadingScreen<T,L,G> as geng_core::state::State>::transition
  11: <geng_core::state::manager::StateManager as geng_core::state::State>::update
  12: geng_core::context::run
  13: geng::run
  14: aicup2019::run_with
  15: aicup2019::run
  16: std::rt::lang_start::{{closure}}
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
  19: std::rt::lang_start_internal
  20: main
</details>

**Comment by kuviman** [comment]
Will be fixed soon. Until then, you need to start the app with terminal from the containing directory

**Comment by kuviman** [comment]
Should have been fixed yesterday
