### ISSUE TITLE
JavaScript support

### ISSUE THREAD

**Issue by StarveTheEgo** [MailRuChamps/raic-2019#2]
Please, add JavaScript support, if possible ! :-)

**Comment by kuviman** [comment]
We want to add JavaScript/TypeScript support, but it may take some time

**Comment by StarveTheEgo** [comment]
If someone from community (maybe, me) will port those client files to JS (from Python, for example), will it be faster?

**Comment by kuviman** [comment]
Yes, but keep in mind that all current clients (model files) are generated from the model of the game, so it would be better if you do this in a way that we can adopt it to autogeneration for faster updates if needed and availability of javascript next time

**Comment by StarveTheEgo** [comment]
Honestly i am not sure how to adopt it to autogeneration, except following existing models structure and code style

**Comment by StarveTheEgo** [comment]
Ported like 70% of code, will finish next night (doing it at nights, meh)

**Comment by StarveTheEgo** [comment]
https://github.com/StarveTheEgo/raic-2019/tree/javascriptsupport

Ok, so i managed to be sleepy af
Here is my not-really-working javascript port...

It hangs while trying to read first boolean flag about **weapon** of first **Unit**. So i assume something goes wrong about reading offsets, so probably at this moment it consumes a bit more socket data than it should do.

I think problem is in **stream-wrapper.js**, but sleepy me, cannot determine what exact one. Maybe problem is about obsolete read-call somewhere in my ported models also... I will try to determine myself, but as i said, i am sleeping already.

Can someone, please, review and fix this one?

**Comment by StarveTheEgo** [comment]
Here is my PR #37

**Comment by StarveTheEgo** [comment]
I would like to know ETA of JS support :-)

_To be honest, that "sandbox" period makes me feel weird about this. Sandbox, by common sense, should not affect tournament brackets, but somehow it selects 1080 participants for Round 1. So we, without specific languages support, should just sit and wait until sandbox ends (50% of sandbox time passed already). I am not sure if i'll submit some temporary Python solution, will i be able to change language later? Almost off-topic_

**Comment by kuviman** [comment]
Should be added in couple of days max. Sandbox will be reset when beta ends

**Comment by kuviman** [comment]
JavaScript added
