### ISSUE TITLE
localrunner flickering

### ISSUE THREAD

**Issue by Karloid** [MailRuChamps/raic-2019#22]
Мерцает дебаг вывод в локал раннере - видео в архиве
[every_tick_debug_short.zip](https://github.com/MailRuChamps/raic-2019/files/3902976/every_tick_debug_short.zip)

стратегия первым же действием рисует линию между собой и врагом
```
    override fun getAction(unit: model.Unit, game: Game, debug: Debug): UnitAction {
        debug.draw(CustomData.Line(game.units[0].position, game.units[1].position, 1 / 30f, ColorFloat(1f, 0f, 0f, 1f)))

```

**Comment by kuviman** [comment]
Мерцание связано с тем, каждый тик начинается с пустого дебага - пока вы не пришлете данные, они рисоваться не будут. А после того как прислали все данные за тик - всключая все действия юнитов, начинается новый тик.

Можно поставить брейкпойнт перед отправкой действий либо воспользоваться перемоткой.

**Comment by Karloid** [comment]
Будет я ли это поведение правиться? Кажется что в codeball не было никакого мерцания при выводе дебагай и что это было удобнее

**Comment by prospero78** [comment]
Дебаг можно выводить в последнюю очередь в кадре. Вообще проблем не вижу. И кстати, регулировка скорости прокрутки при каждом запуске -- это бага. Сделайте сохранение конфига.

**Comment by kuviman** [comment]
В codeball отрисовывалась старая информация поверх нового тика, соответственно дебаг с реальностью не совпадал.

Дебаг выводится в последнюю очередь в кадре, проблема в том что кадры и тики - разные вещи

Планируется прийти к какому то решению, которое бы работало и в реалтайме без мерцаний и при дебаге.

**Comment by aka-npou** [comment]
Флаг запуска. Или рисовать сразу или потом все. Если флаг то для последнего тика брать предыдущий тик дебаг. При перемотке тогда будут старые тики в тики, а последний рисовать предыдущий тик дебаг.

**Comment by kuviman** [comment]
Исправлено (последний тик рисует дебаг данные с прошлого тика, если не стоять именно на последнем тике долгое время)
