### ISSUE TITLE
Go: массовые ошибки

### ISSUE THREAD

**Issue by prospero78** [MailRuChamps/raic-2019#26]
main.go: should not use dot imports
  main.go: exported type Runner should have comment or be unexported
  main.go: exported function NewRunner should have comment or be unexported
  main.go: exported method Runner.Run should have comment or be unexported

  my_strategy.go: should not use dot imports

  debug.go: should not use dot imports
  debug.go: exported type Debug should have comment or be unexported
  debug.go: exported method Debug.Draw should have comment or be unexported

go.mod: зачем вы впихнули модули? Вы используете версии? Боитесь сами у себя удалить зависимости? Чтобы невозможно было создать свой пакет? (а при попытке импортировать модуль "../ai2019/module" -- сделать это невозможно, хоть по системном пути, хоть вне системного пути).

    $ go get github.com/MailRuChamps/raic-2019/...
    
    package github.com/MailRuChamps/raic-2019/clients/go
        imports aicup2019/model: unrecognized import path "aicup2019/model" (import path does not begin with hostname)
    package github.com/MailRuChamps/raic-2019/clients/go
        imports aicup2019/stream: unrecognized import path "aicup2019/stream" (import path does not begin with hostname)`

**Comment by CthulhuDen** [comment]
Вот не нужно только от модулей отказываться, с ними в 1000 раз удобнее. Просто распакуй код куда-то вне gopath и вызывай go build (на го 1.13)

**Comment by prospero78** [comment]
НЕ РАБОТАЕТ. Я же вне системного пути и распаковываю.
В модулях смысла не вижу. Версия тебе нужна? Ну создай каталог с нужным номером версии и пользуй его (go mod в сущности именно это и делает, руками лень папочку создать?).

**Comment by StarveTheEgo** [comment]
Пошто сообщения-то такие эмоциональные? :(
Это только мешает...

**Comment by kuviman** [comment]
Текущий языковой пакет должен работать. Если вы хотите, вы можете менять все файлы пакета при отправке своей стратегии
