### ISSUE TITLE
Черный экран при перенаправлении stderr

### ISSUE THREAD

**Issue by SSS135** [MailRuChamps/raic-2019#29]
Пытаюсь перенаправить поток вывода ошибок у локалранера. В --batch-mode работает нормально, а с графикой черный экран. Нужно это для отслеживания запуска приложения (ожидание INFO - Waiting for connection on port), чтобы потом подключиться к нему из своего кода и обучать нейронку. Можно проверить примерно таким кодом на питоне. Если убрать `stderr=PIPE`, то всё работает. 
```
from subprocess import Popen, PIPE
proc = Popen(['localrunner/aicup2019.exe'], cwd='localrunner', 
    stdout=PIPE, stdin=PIPE, stderr=PIPE)
```

**Comment by kuviman** [comment]
Если вы не читаете данные из потока, это блокирует приложение при выводе в stderr

`proc.communicate()` исправляет ситуацию
