### ISSUE TITLE
team_size = 2 - нет управления вторым юнитом. Возможно, ошибка в нумерации игроков в ЛР

### ISSUE THREAD

**Issue by Nirenamid** [MailRuChamps/raic-2019#31]
Запустил локально игру сам с собой (с двумя юнитами в каждой команде). И не смог получить управление вторым юнитом. Есть подозрение, что на стороне локал-раннера некорректно нумеруются id-шники игроков, в итоге получается не 2 команды по 2 юнита, а 4 - по 1. Воспроизвести можно примерно так:
![image](https://user-images.githubusercontent.com/18709286/69890629-db1c8680-1307-11ea-8606-0ea2d6d68ee6.png)

Вывод первого игрока:
```
player_view.my_id = 1

	player_id  	id
	1		2	Its MY unit!
	3		4
	5		6
	7		8
```
и второго:
```
player_view.my_id = 3

	player_id  	id
	1		2
	3		4	Its MY unit!
	5		6
	7		8
```
В итоге по одному юниту в каждой команде - не получают управления и неподвижно стоят.

**Comment by Nirenamid** [comment]
Переформулирую вопрос :)
Как запустить в LR игру с `team_size = 2`, и можно ли это сейчас? 
Или до начала 2-го раунда даже не стоит пытаться?

**Comment by kuviman** [comment]
Было исправлено
