### ISSUE TITLE
Archive for Linux

### ISSUE THREAD

**Issue by Davarg** [MailRuChamps/raic-2019#36]
Can‘t extract files from archive for Linux

Output:
tar: This does not look like a tar archive 
tar: Skipping to next header 
tar: Exiting with failure status due to previous errors

**Comment by kuviman** [comment]
```sh
mkdir aicup-app && cd aicup-app
wget https://russianaicup.ru/s/123/assets/app/aicup2019-linux.tar.gz
tar xzf aicup2019-linux.tar.gz
./aicup2019
```
