### ISSUE TITLE
Kotlin send strategy

### ISSUE THREAD

**Issue by Timashkov** [MailRuChamps/raic-2019#41]
Если отправить архивом стратегию, то на попытке компиляции на сервере получаем ошибку, что не хватает файлов проекта для сборки

stdout:
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.210 s
[INFO] Finished at: 2019-12-01T10:26:45Z
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/project). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

stderr:
+ '[' compile '!=' base ']'
++ ls -1 /src/
++ wc -l
+ [[ 5 -eq 1 ]]
+ rm -rf ./Dockerfile ./compile.sh ./pom.xml ./run.sh ./src ./target
+ cp -rf /src/Debug.kt /src/MyStrategy.kt /src/Runner.kt /src/model /src/util ./
+ mvn package --batch-mode

**Comment by Timashkov** [comment]
Отправка на сервер №1195 , если это как-то поможет

**Comment by kuviman** [comment]
В случае отправки стратегии zip-файлом, необходимо сохранить ту же структуру, что и исходный языковой пакет — отправляйте все файлы, в корне архива должны лежать файлы проекта
