### ISSUE TITLE
jumpState.canJump = false, если тик завершился "прилипанием" к потолку

### ISSUE THREAD

**Issue by tyamgin** [MailRuChamps/raic-2019#42]
Стратегия для повторения:
```
        if (currentTick == 0) {

        } else if (currentTick == 1) {
            action.velocity = 10;
        } else {
            action.jump = true;
        }
```
Как видно, она просто прыгает и бьётся об потолок.
Ровно на конец тика №127 так совпало, что юнит остаётся прижатым к потолку. На 128-й тик уже приходит canJump = fasle.

Это баг, или как нужно трактовать такую ситуацию?

**Comment by kuviman** [comment]
При столкновении с потолком прыжок прекращается, => `canJump = false`

**Comment by tyamgin** [comment]
При полете вниз canJump тоже = fasle.
Я затупил, простите.
