### ISSUE TITLE
Не грузится график рейтинга в профиле пока не переключишь период

### ISSUE THREAD

**Issue by Karloid** [MailRuChamps/raic-2019#50]
![image](https://user-images.githubusercontent.com/2398460/70082971-90a74c80-161c-11ea-8739-12157c263dee.png)
Не грузится и в мобильном сафари и в браузерном хроме, не грузится во всех профайлах

**Comment by silentnox** [comment]
Кстати да

**Comment by kuviman** [comment]
Fixed
