### ISSUE TITLE
Некорректная позиция юнитов (метод getPosition java-клиент)

### ISSUE THREAD

**Issue by SobornovDev** [MailRuChamps/raic-2019#63]
Метод getPosition возвращает возвращает некорректные значения для класса Unit. Судя по документации поле position: Vec2⟨float64⟩— позиция (середина нижней границы). Однако на практике при смене вектора движения, при подборе предметов, либо при "слипании" юнитов возвращаемые значения не являются корректными. Ниже скриншоты, в дебаге выведены методы getPosition().getX()  / getPosition().getY() для юнита игрока и для юнита соперника.
Обратите внимание на то, как меняется значение EnemyX / EnemyY для двух соседних тиков.
![подбор предмета1](https://user-images.githubusercontent.com/47084113/70328326-cf6e1a00-1849-11ea-9e61-a4532adc430a.png)
![подбор предмета2](https://user-images.githubusercontent.com/47084113/70328331-d006b080-1849-11ea-845d-cfeabf980d05.png)
![смена вектора движения1](https://user-images.githubusercontent.com/47084113/70328327-cf6e1a00-1849-11ea-8392-07231d39fe3c.png)
![смена вектора движения2](https://user-images.githubusercontent.com/47084113/70328329-d006b080-1849-11ea-922d-df292479bf32.png)
![слипание](https://user-images.githubusercontent.com/47084113/70328330-d006b080-1849-11ea-92c2-4ced40c0709c.png)

**Comment by kuviman** [comment]
Скорее всего проблема у вас
