### ISSUE TITLE
В C++ клиенте в методах writeTo ряда классов  ошибка в выражении условия

### ISSUE THREAD

**Issue by rzndev** [MailRuChamps/raic-2019#67]
В методе writeTo классов Bullet, Mine, ServerMessageGame, Unit, Weapon, WeaponParams ошибка в выражении условия, например,

if (explosionParams) {
        stream.write(false);
    } else {
        stream.write(true);
        (*explosionParams).writeTo(stream);
    }

**Comment by tyamgin** [comment]
Действительно. А где используется Bullet::writeTo?

**Comment by kuviman** [comment]
Нигде не используется. Но исправили
