### ISSUE TITLE
Ошибка клиента при попытке отрисовать линию

### ISSUE THREAD

**Issue by nutic** [MailRuChamps/raic-2019#68]
```
debug.draw(model.CustomData.Line(target_pos, target_pos, 1.0, model.ColorFloat(255, 0, 0, 1.0)))
```
валит клиент с ошибкой:
`ERROR - panicked at 'Unexpected discriminant 1065353216', /builds/aicup/2019/app/.cache/.cargo/git/checkouts/codegame-5bdec12bd92d3b8a/a2502d0/src/lib.rs:86:34
 `

**Comment by kuviman** [comment]
`CustomData` принимает `Float` во всех объектах. Необходимо конвертировать `target_pos` из `Vec2Double` в `Vec2Float`
