### ISSUE TITLE
Скорость по умолчанию в плеере

### ISSUE THREAD

**Issue by Oreshnik** [MailRuChamps/raic-2019#72]
Пожалуйста, сделайте скорость по умолчанию в плеере поменьше, хотя бы 30 TPS. Сейчас очень быстро, ничего нельзя разобрать. Каждый раз приходится останавливать, отматывать, менять скорость. Скорость менять тоже неудобно, потому что максимум - нереальные 500, на которых никто смотреть не будет. Лично я всегда настраиваю в левой четверти. Может и 500 подрезать до 200 хотя бы?

**Comment by Jeen99** [comment]
Дополнительно можно добавить значение в конфиг, чтобы каждый под себя мог настроить.

**Comment by tyamgin** [comment]
И запоминать на сайте настройки.

**Comment by kuviman** [comment]
Настройки теперь запоминаются между запусками
