### ISSUE TITLE
Javascript draw CustomData.Line Error

### ISSUE THREAD

**Issue by montylab** [MailRuChamps/raic-2019#77]
вылетает стратегия, при отрисовке линии.
Нашел на других языках была проблема с Vec2Double, но замена на Vec2Float не помогла, что-то еще не так? 

debug.draw(new CustomData.Line(new Vec2Float(1, 1), new Vec2Float(10, 10), 1, new ColorFloat(1, 0, 0, 1)))

**Comment by StarveTheEgo** [comment]
**await** поставил перед вызовом?

**Comment by montylab** [comment]
да, спасибо, потерял await
