### ISSUE TITLE
2x2 Windows App Aiming and Shooting Bug

### ISSUE THREAD

**Issue by alvinalvord** [MailRuChamps/raic-2019#86]
There seems to be a bug in aiming and shooting on the windows app 2x2.
---
Basically here is what I did: 
1. Find allied unit (ally.playerId == unit.playerId && ally.Id != unit.Id)
2. The unit with the lower ID aims at (-40, -40) and shoot = true
3. The unit with the higher ID aims at (40, 40) and shoot = false
---
The result is:
* Both controlled units have the same last aim angle
* Both controlled units are not shooting
---
Here is a screenshot:
![Image](https://i.ibb.co/jRydT5Z/Capture.jpg)
* Unit 128 should be shooting and aiming towards (-40, -40) but is not doing both

**Comment by kuviman** [comment]
Looks like that one is bug in your code

**Comment by alvinalvord** [comment]
Okay, i found the problem. Apparently I shouldn't reuse the unit action object. The problem fixes itself when I reinitialize a new unit action every time get action is called. I've inserted the code I've been testing for a while :)) thanks anyway.

``` java
import model.*;

public class MyStrategy {
	UnitAction action;
	
	MyStrategy () {
		action = new UnitAction ();
	}
	
	public UnitAction getAction(Unit unit, Game game, Debug debug) {
		Unit ally = null;
		Unit enemy = null;
		for (Unit u: game.getUnits ()) {
			if (u.getPlayerId () == unit.getPlayerId () && u.getId () != unit.getId ()) {
				ally = u;
			} else if (u.getPlayerId () != unit.getPlayerId ()) {
				enemy = u;
			}
		}

		// uncomment to fix bug lol
		// action = new UnitAction();
		if (ally != null && unit.getId () < ally.getId ()) {
			action.setAim (new Vec2Double (-40, 0));
			action.setShoot (true);
		} else {
			action.setAim (new Vec2Double (40, 0));
			action.setShoot (false);
		}
		
		action.setVelocity (enemy.getPosition ().getX () - unit.getPosition ().getX ());
		action.setJump (enemy.getPosition ().getY () > unit.getPosition ().getY ());
		action.setJumpDown (false);
		action.setReload (false);
		action.setSwapWeapon(false);
		action.setPlantMine(false);
		return action;
	}
}
```
